server:
  port: 9097
      
ribbon:
  eureka:
    enabled: true
    
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

## PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_venda
    username: postgres
    password: postgres

#drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false