server:
  port: 9093

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2
    
#eureka.client.service-url.instance=
#eureka.client.service-url.leaseRenewalIntervalInSeconds= 1
#eureka.client.service-url.leaseExpirationDurationInSeconds= 2

## PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_funcionario
    username: postgres
    password: postgres

#drop n create table again, good for testing, comment this in production
  jpa:
    hibernate:
      ddl-auto: create
      
    show-sql: false
